# Generated by Django 3.2.9 on 2021-11-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, max_length=5000, null=True, upload_to=''),
        ),
    ]
