# Generated by Django 3.2.9 on 2021-11-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0006_auto_20211120_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', null=True, upload_to='path/to/dir/for/images/'),
        ),
    ]
