# Generated by Django 3.2.9 on 2021-11-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0008_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
