# Generated by Django 3.2.9 on 2021-11-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0009_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
