# Generated by Django 3.2.9 on 2021-11-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0010_auto_20211120_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, db_column='Image', null=True, upload_to='onlineshoes\\media\\images'),
        ),
    ]
