# Generated by Django 3.2.9 on 2021-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0011_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, db_column='Image', null=True, upload_to='path/to/dir/for/images/'),
        ),
    ]
