# Generated by Django 3.2.9 on 2021-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0014_rename_cover_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', default='', null=True, upload_to='epic/images/'),
        ),
    ]
