# Generated by Django 3.2.9 on 2021-11-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0017_auto_20211120_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
